[[redirects]]
  from = "/en"
  to = "/?lang=en"
  status = 301

[[redirects]]
  from = "/en/"
  to = "/?lang=en"
  status = 301

[[redirects]]
  from = "/en/*"
  to = "/?lang=en"
  status = 301

[[redirects]]
  from = "/zh"
  to = "/?lang=zh"
  status = 301

[[redirects]]
  from = "/zh/"
  to = "/?lang=zh"
  status = 301

[[redirects]]
  from = "/zh/*"
  to = "/?lang=zh"
  status = 301

[[redirects]]
  from = "/fr"
  to = "/"
  status = 301

[[redirects]]
  from = "/fr/"
  to = "/"
  status = 301
